javaVersion=21
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.8
minecraft_version_range=>=1.21.6
loader_version=0.17.2
loader_version_range=>=0.17.2
fabric_version=0.133.4+1.21.8

mod_license=LGPL-3.0-only
resource_pack_format=64
data_pack_format=81
modDependencies=[]
modSides=[ "client", "server" ]

modmenu_version=15.0.0-beta.3

fabric.loom.multiProjectOptimisation=false
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
