javaVersion=25
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1.2
minecraft_version_range=>=26.1.2
loader_version=0.18.6
loader_version_range=>=0.19.1
fabric_version=0.146.0+26.1.2

mod_license=LGPL-3.0-only
resource_pack_max_format=84
resource_pack_min_format=82
data_pack_format=101
modDependencies=[]
modSides=[ "client", "server" ]

modmenu_version=18.0.0-alpha.8

fabric.loom.multiProjectOptimisation=false
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

loom_version=1.16-SNAPSHOT